pipelines:
  branches:
    pipelines:
      - step:
          name: Assemble .env file
          deployment: demo-compile
          script:
            - chmod +x ./env.sh
            - bash ./env.sh
            - cat ./.env
          artifacts:
            - .env
      - step:
          image: node:18
          name: Create development build
          caches:
            - node
          script:
            - npm install
            - npm run generate
          artifacts:
            - .output/public/**
    demo:
      - step:
          name: Assemble .env file
          deployment: demo-compile
          script:
            - chmod +x ./env.sh
            - bash ./env.sh
          artifacts:
            - .env
      - step:
          image: node:18
          name: Create development build
          caches:
            - node
          script:
            - npm install
            - npm run generate
          artifacts:
            - .output/public/**
      - step:
          name: Deploy to Demo
          deployment: demo
          script:
            - pipe: atlassian/ftp-deploy:0.4.0
              variables:
                USER: $FTP_USERNAME
                PASSWORD: $FTP_PASSWORD
                SERVER: $FTP_HOST
                REMOTE_PATH: $FTP_PATH
                LOCAL_PATH: .output/public
                EXTRA_ARGS: '--exclude .htaccess --exclude backend/'
                DEBUG: 'true'
                DELETE_FLAG: 'true'
    dev:
      - step:
          name: Assemble .env file
          deployment: prod-compile
          script:
            - chmod +x ./env.sh
            - bash ./env.sh
          artifacts:
            - .env
      - step:
          image: node:18
          name: Create development build
          caches:
            - node
          script:
            - npm install
            - npm run build
          artifacts:
            - .output/**
      - step:
          # image: wagnerstephan/bitbucket-git-ftp:latest
          name: Deploy to Production
          deployment: prod
          script:
            # - git ftp push --auto-init -v --user $FTP_USERNAME --passwd $FTP_PASSWORD $FTP_PROTOCOL://$FTP_HOST$FTP_PATH
            - pipe: atlassian/ftp-deploy:0.4.0
              variables:
                USER: $FTP_USERNAME
                PASSWORD: $FTP_PASSWORD
                SERVER: $FTP_HOST
                REMOTE_PATH: '${FTP_PATH}build/${BITBUCKET_BUILD_NUMBER}'
                # REMOTE_PATH: '${FTP_PATH}build; mv ${FTP_PATH}.output ${FTP_PATH}old && mv ${FTP_PATH}build ${FTP_PATH}.output && mrm -r ${FTP_PATH}old/'
                LOCAL_PATH: .output
                # EXTRA_ARGS: 'mv $FTP_PATH/test $FTP_PATH/old && mv $FTP_PATH/build/output $FTP_PATH/ && mrm -r $FTP_PATH/old/'
                SET_ARGS: "ftp:ssl-allow true  mirror:parallel-transfer-count 10"
                DEBUG: 'true'
                DELETE_FLAG: 'true'

  custom:
    regenerate:
      - step:
          name: Assemble .env file
          deployment: demo-compile
          script:
            - chmod +x ./env.sh
            - bash ./env.sh
          artifacts:
            - .env
      - step:
          image: node:18
          name: Create development build
          caches:
            - node
          script:
            - npm install
            - npm run generate
          artifacts:
            - .output/public/**
      - step:
          name: Deploy to Demo
          deployment: demo
          script:
            - pipe: atlassian/ftp-deploy:0.4.0
              variables:
                USER: $FTP_USERNAME
                PASSWORD: $FTP_PASSWORD
                SERVER: $FTP_HOST
                REMOTE_PATH: $FTP_PATH
                LOCAL_PATH: .output/public
                EXTRA_ARGS: '--exclude .htaccess --exclude backend/'
                DEBUG: 'true'
                DELETE_FLAG: 'true'

definitions:
  caches:
    node: node_modules
